#!/bin/sh
#
# chkconfig:	345 91 35
# description:	Regenerates issue* files for issue-fancy (they \
#		contain uptime).
#

export PATH=/bin:/sbin:/usr/bin:/usr/sbin

# Source function library.
. /etc/rc.d/init.d/functions


case "$1" in
  start|restart|force-reload)
	issue-fancy-gen
	;;
  stop|status)
	# Yap, do *nothing*, but accept argument.
	;;
  *)
	msg_usage "$0 {start|stop|restart|force-reload|status}"
	exit 3
esac

exit 0
